# Generated by Django 3.2.23 on 2024-08-15 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='head_teacher',
            new_name='class_teacher',
        ),
    ]
